level = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                              DD   W",
    "W         WWWWWW               DD   W",
    "W   WWWW       W         WWW        W",
    "W   W        WWWW                   W",
    "W WWW  WWWW                         W",
    "W   W     WW       WWW     WWW      W",
    "W   W     W   WWWW    W             W",
    "W   WWW WWW     W      W            W",  
    "W     W   W     W      W            W",   
    "W WW   W   WW   WW     WWWWWWW      W",                
    "W W      WW               WW        W",                 
    "W W   WWWW    PP                    W",                 
    "W     W       PP                    W",
    "W                      WWWWW        W",
    "W                                   W",   
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    ]

